package main

var colonValueServices = map[string]bool{
	"app_binding":              true,
	"content":                  true,
	"dbinfo":                   true,
	"hardware_properties":      true,
	"launcher":                 true,
	"locksettings":             true,
	"media_metrics":            true,
	"media_resource_monitor":   true,
	"media_projection":         true,
	"media_communication":      true,
	"package_native":           true,
	"permission_checker":       true,
	"permissionmgr":            true,
	"pinner":                   true,
	"platform_compat":          true,
	"platform_compat_native":   true,
	"recovery":                 true,
	"runtime":                  true,
	"scheduling_policy":        true,
	"sdk_sandbox":              true,
	"serial":                   true,
	"storaged":                 true,
	"storaged_pri":             true,
	"storagestats":             true,
	"system_config":            true,
	"testing":                  true,
	"textclassification":       true,
	"textservices":             true,
	"thermalservice":           true,
	"updatelock":               true,
	"usagestats":               true,
	"virtualdevice":            true,
	"wifi_aware":               true,
	"wifi_rtt":                 true,
	"wifi_scanner":             true,
	"batteryproperties":        true,
	"appwidget":                true,
	"clipboard":                true,
	"device_policy":            true,
	"input_method":             true,
	"media_session":            true,
	"network_management":       true,
	"permission":               true,
	"print":                    true,
	"processinfo":              true,
	"procstats":                true,
	"role":                     true,
	"sensorservice":            true,
	"statusbar":                true,
	"telecom":                  true,
	"trust":                    true,
	"uimode":                   true,
	"vibrator":                 true,
	"wallpaper":                true,
	"connectivity_native":      true,
	"netpolicy":                true,
	"safety_center":            true,
	"voiceinteraction":         true,
	"webviewupdate":            true,
	"network_score":            true,
	"translation":              true,
	"account":                  true,
	"audio":                    true,
	"connectivity":             true,
	"media":                    true,
	"mount":                    true,
	"nfc":                      true,
	"settings":                 true,
	"shortcut":                 true,
	"network_time_update_service": true,
	"search":                   true,
}

func isColonValueDumpsys(args []string) bool {
	if len(args) == 2 && args[0] == "dumpsys" {
		return colonValueServices[args[1]]
	}
	return false
}
